### PR TITLE
Added the OLED default BGRT startup logo

### PR DESCRIPTION
**Pull request by annson24**
Size and color should be 100% accurate.

### CODE REVIEW

**Comment by ryanrudolfoba** [comment]
Thanks for this! How did you get it from OLED? I was poking around my OLED but cant find it.

**Comment by annson24** [comment]
My OLED is still on its way so idk if it has an unmodified OLED logo but my LCD has this deck_boot_transition.png which (of course) is the old logo, so I just modified it, I took the exact color hex code from the OLED startup video to be accurate. If you want to check yours out, go to 'Home/.local/share/Steam/steamui/images', the deck_boot_transition.png or rather the oled_boot_transition.png should be there.

**Comment by annson24** [comment]
Hey there, I found the actual (unedited) bootsplash the oled in rootfs/usr/share/plymouth/themes/steamos. Is it legal to use it here or should we stick with the initial one I edited? I don't want to make a pull request here just for valve to strike a DMCA.

**Comment by ryanrudolfoba** [comment]
i think what you provided will be sufficient. i'll add it to my other repo Steam Deck Logo Changer.

**Pull request merged**
